name:  C/C++ code linter

on: [pull_request]
jobs:
  C/C++ code linter:
    name: C/C++ code linter
    runs-on: ubuntu-latest
    steps:
      - name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
        uses: ArtificialAmateur/cpp-linter-action@0.01
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
